export const SPECIALIZATION_CREATE_REQUEST = "SPECIALIZATION_CREATE_REQUEST";
export const SPECIALIZATION_CREATE_SUCCESS = "SPECIALIZATION_CREATE_SUCCESS";
export const SPECIALIZATION_CREATE_FAIL = "SPECIALIZATION_CREATE_FAIL";
export const SPECIALIZATION_CREATE_RESET = "SPECIALIZATION_CREATE_RESET";

export const SPECIALIZATION_LIST_REQUEST = "SPECIALIZATION_LIST_REQUEST";
export const SPECIALIZATION_LIST_SUCCESS = "SPECIALIZATION_LIST_SUCCESS";
export const SPECIALIZATION_LIST_FAIL = "SPECIALIZATION_LIST_FAIL";

export const SPECIALIZATION_UPDATE_REQUEST = "SPECIALIZATION_UPDATE_REQUEST";
export const SPECIALIZATION_UPDATE_SUCCESS = "SPECIALIZATION_UPDATE_SUCCESS";
export const SPECIALIZATION_UPDATE_FAIL = "SPECIALIZATION_UPDATE_FAIL";
export const SPECIALIZATION_UPDATE_RESET = "SPECIALIZATION_UPDATE_RESET";

export const SPECIALIZATION_DELETE_REQUEST = "SPECIALIZATION_DELETE_REQUEST";
export const SPECIALIZATION_DELETE_SUCCESS = "SPECIALIZATION_DELETE_SUCCESS";
export const SPECIALIZATION_DELETE_FAIL = "SPECIALIZATION_DELETE_FAIL";

export const SPECIALIZATION_TOGGLE_REQUEST = "SPECIALIZATION_TOGGLE_REQUEST";
export const SPECIALIZATION_TOGGLE_SUCCESS = "SPECIALIZATION_TOGGLE_SUCCESS";
export const SPECIALIZATION_TOGGLE_FAIL = "SPECIALIZATION_TOGGLE_FAIL";

export const SPECIALIZATION_DETAILS_REQUEST = "SPECIALIZATION_DETAILS_REQUEST";
export const SPECIALIZATION_DETAILS_SUCCESS = "SPECIALIZATION_DETAILS_SUCCESS";
export const SPECIALIZATION_DETAILS_FAIL = "SPECIALIZATION_DETAILS_FAIL";
